### ISSUE TITLE
Better default for NUTS

### ISSUE THREAD

**Issue by junpenglao** [drbenvincent/darc-analysis-python#1]
Glad to see you are making progress in your toolbox, it is looking nice! ;-)
I have one suggestion of the set up in the sampler:
https://github.com/drbenvincent/darc-analysis-python/blob/692f6a25b88e247de1e3b33bc9258a5a0ad6b1ae/models_solo.py#L46-L48

Doing this you cannot take advantage of the mass matrix adaptation of NUTS in the `pm.sample`. You should instead do
```python
with model:
    trace = pm.sample(nsamples, chains=2, njobs=2, tune=tune, 
                                   nuts_kwargs=dict(target_accept=target_accept))
```
Which will run the default tunning.
In the simpler models, it probably makes no differences, but for a more complicated model like the mixture model you might see some improvement.

**Comment by drbenvincent** [comment]
Thanks :) Have implemented now - although it's not solved the issue with the mixture model yet. Will get to that at some point ;)

**Comment by junpenglao** [comment]
Yeah you should use the proper fix for mixture. Either [Ordered transformation](https://nbviewer.jupyter.org/gist/junpenglao/4d65d1a9bf80e8d371446fadda9deb7a#Enforcing-an-Ordering) or [adding a potential as constraint](https://nbviewer.jupyter.org/gist/junpenglao/4d65d1a9bf80e8d371446fadda9deb7a#Enforcing-an-Ordering-(Using-potential)) should do.
