### ISSUE TITLE
fix convergence for DoubleExponential (is a mixture model)

### ISSUE THREAD

**Issue by drbenvincent** [drbenvincent/darc-analysis-python#2]
We get non-convergence for the chains for the `DoubleExponential` model. @junpenglao pointed me to Either Ordered transformation or adding a potential as constraint should do (see https://nbviewer.jupyter.org/gist/junpenglao/4d65d1a9bf80e8d371446fadda9deb7a#Enforcing-an-Ordering-(Using-potential))

**Comment by drbenvincent** [comment]
Basically this now works reliably. I've tested it on data from multiple participants. Sometimes you need to increase the number of tuning samples, but I'm happy that this works. 

Example A
<img width="793" alt="screen shot 2018-01-29 at 10 44 59" src="https://user-images.githubusercontent.com/6765047/35506852-aabf4624-04e2-11e8-8d87-bb4b257a6ceb.png">
<img width="787" alt="screen shot 2018-01-29 at 10 45 09" src="https://user-images.githubusercontent.com/6765047/35506853-aadbba02-04e2-11e8-84d7-89d17e4095fb.png">

Example B
Interesting that in many of the participants, the double exponential model just seems to be allowing for a shift in the intercept of the discount function. In that way it's a superficially like the beta delta function
<img width="791" alt="screen shot 2018-01-29 at 10 57 01" src="https://user-images.githubusercontent.com/6765047/35507202-e5333ada-04e3-11e8-836f-61272451f268.png">

**Comment by junpenglao** [comment]
That's great! Please add this package to https://github.com/pymc-devs/pymc3#software-using-pymc3 whenever you think it is ready ;-)
